# Generated by Django 5.2.6 on 2025-10-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotina',
            name='dias',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rotina',
            name='horario_fim',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='rotina',
            name='horario_inicio',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
