# Generated by Django 5.2.5 on 2025-09-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='turma2',
            name='alunos',
        ),
        migrations.AddField(
            model_name='aluno2',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.turma2'),
        ),
    ]
