# Generated by Django 5.2.5 on 2025-09-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_remove_aluno2_email_remove_turma2_alunos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade2',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atividade2',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade2',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
