# Generated by Django 5.2.5 on 2025-11-29 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_compromisso'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('seg', 'Segunda'), ('ter', 'Terça'), ('qua', 'Quarta'), ('qui', 'Quinta'), ('sex', 'Sexta'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CompromissoRecorrenciaExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('compromisso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes', to='projeto.compromisso')),
            ],
        ),
    ]
