# Generated by Django 5.2.5 on 2025-09-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_atividade2_ativa_atividade2_horario_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade2',
            name='ativa',
        ),
    ]
