# Generated by Django 5.2.5 on 2025-09-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_remove_atividade2_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade2',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
    ]
