# Generated by Django 5.2.5 on 2025-09-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_atividade2_ativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade2',
            name='ativa',
        ),
    ]
